### ISSUE TITLE
can't get IANA zone name with `TZ=:/etc/localtime`

### ISSUE THREAD

**Issue by scottlamb** [BurntSushi/jiff#113]
I have a https://github.com/scottlamb/moonfire-nvr branch that adopts `jiff`. It seems to be working well, except for one annoying little thing.

My [installation instructions](https://github.com/scottlamb/moonfire-nvr/blob/6c587c1b2e64d8aa4cbe300fd77bdd9016481182/guide/install.md#starting-it-up) currently say to set `TZ=:/etc/localtime` to avoid libc repeatedly checking if `/etc/localtime` has changed, as described in [this blog post](https://blog.packagecloud.io/set-environment-variable-save-thousands-of-system-calls/). (In my case, this is both an optimization and for correctness, as my software's indices of what happened in a given day might give strange results if time zone definitions change during operation.)

If I have `TZ` set in this way, `jiff::tz::TimeZone::system().iana_name().unwrap()` fails. Looks like it reads the file but doesn't resolve the symlink (thus know the zone name from the filename) as it would without the colon or without `TZ` at all.

I specifically put `TZ=:/etc/localtime` rather than e.g. `TZ=:America/Los_Angeles` so folks can just copy'n'paste it and have it match their system zone, rather than having to edit the file when they install and if they later change their zone.

I'll take out the `TZ=:/etc/localtime` from my new install instructions when updating to `jiff` (as `jiff` doesn't seem to check the zone for updates anyway). But...I have users who already followed the old instructions. I'd like it to just work without changes. Easier, and otherwise inevitably someone will forget say the `sudo systemctl daemon-reload` (or Docker equivalent) to make it take effect, see the error, and get confused.

Could `jiff` resolve the symlink in this case to get the zone name properly?

**Comment by BurntSushi** [comment]
Yes, I think Jiff can look for symlink metadata in this case. I don't see any particular problem with that and it seems like a good idea.

Do note though that `jiff::tz::TimeZone::system().iana_name().unwrap()` can still fail even if this were fixed. For example, if `/etc/localtime` isn't a symlink.

**Comment by BurntSushi** [comment]
I've got a fixed up in #115 

The article you linked is interesting. I would not necessarily expect `TZ=:/etc/localtime` to suppress re-checking `/etc/localtime` to see if it changed. Certainly not something that can be relied upon as I don't think that's specified behavior?

Jiff's caching is a bit different. Possibly naive. It uses a simple TTL, that once expired, it will re-load the time zone from `TZ` if it's set. I do expect this caching strategy to evolve and harden over time, and I didn't think there was any realistic way of me getting it right out of the gate in isolation. So I started very simple. If you run into problems with it, please file issues! (There is a lot of unexplored space IMO.)

**Comment by BurntSushi** [comment]
This is fixed on crates.io in `jiff 0.1.10`.

**Comment by scottlamb** [comment]
Thank you!

> Certainly not something that can be relied upon as I don't think that's specified behavior?

No, probably not, but it was the best I knew how to do with the tools available at the time.

> Jiff's caching is a bit different. Possibly naive. It uses a simple TTL, that once expired, it will re-load the time zone from TZ if it's set

Oh, good to know, thanks. So `jiff::tz::TimeZone::system()` can potentially return different values over the lifetime of the process, but a given `jiff::tz::TimeZone` once returned is immutable, right? As it happens, I'm holding onto one `TimeZone` forever ([here](https://github.com/scottlamb/moonfire-nvr/blob/d11a46db1e3dbda04c5689f72c28935e7723515a/server/base/time.rs#L27)), so that's just fine for me. I'll just update my comment to mention this.

**Comment by BurntSushi** [comment]
> So `jiff::tz::TimeZone::system()` can potentially return different values over the lifetime of the process, but a given `jiff::tz::TimeZone` once returned is immutable, right?

Yes, that's correct. That also tips the scales a bit in terms of caching. libc has no "time zone" type.
