### ISSUE TITLE
add dedicated RFC 2822 parser and printer

### ISSUE THREAD

**Issue by BurntSushi** [BurntSushi/jiff#16]
While the Temporal grammar covers most of what I think most want out of RFC 3339, RFC 9557 and ISO 8601, it doesn't touch on RFC 2822 at all. I suspect RFC 2822 is used widely enough that including a dedicated parser/printer for it would be advantageous.

**Comment by jhpratt** [comment]
For what it's worth, it is possible to parse `&[u8]` in `time`, it's just not as ergonomic.
