### ISSUE TITLE
Support riscv32imc-unknown-none-elf

### ISSUE THREAD

**Issue by lu-zero** [BurntSushi/jiff#162]
There are few uses of `Arc` and those are missing for the target.
Would it be acceptable to add `portable-atomic` and `portable-atomic-util` and the required knobs to support it?

**Comment by BurntSushi** [comment]
I am okay with it as long as they are only included and used for targets that specifically need them.

Another option is to just not use an `Arc` on those targets and instead use a `Box`. It might lead to higher memory usage and longer clones. This is probably not great, specifically, for the case of `TimeZone` which is really designed to be cheap to clone. So probably the target specific dependency is worth it.

**Comment by BurntSushi** [comment]
I don't have any experience with targets like `riscv32imac-unknown-none-elf`, so this is probably going to require someone other than me to contribute support here.

My main requirement here is that Jiff does not grow more dependencies in the general case. I am okay with target specific dependencies that _carry their weight_. A brief glance suggests that `portable-atomic` does, but I wouldn't want to bring that dependency in for, say, `x86-64` or `aarch64`.

**Comment by lu-zero** [comment]
Let me prepare something, it is `riscv32imc-unknown-none-elf` the problematic one.
