### ISSUE TITLE
Implement `TryFrom<TimeZone> for Offset` for fixed & utc timezones.

### ISSUE THREAD

**Issue by bschoenmaeckers** [BurntSushi/jiff#169]
I would like to convert a TimeZone to an offset without access to a specific instant in time. A try_from/try_into would help me to this and handle the case where it is not possible. A other way of distinguishing fixed offsets from others non on `TimeZone` would also be fine, for example `fn to_fixed_offset(&TimeZone) -> Option<Offset>`.

Please let me know if you think this is a bad idea or not. :)

**Comment by BurntSushi** [comment]
I think this is probably fine, but can you say more about the higher level use case? As in, why do you want this conversion?

**Comment by bschoenmaeckers** [comment]
Which implementation the you prefer. `TryFrom` or a separate method of TimeZone? I am willing to create a PR if you like.

**Comment by bschoenmaeckers** [comment]
> I think a `to_offset` method for now seems the least risky from an API evolution perspective. (Note not `to_fixed_offset` for consistency with other APIs in Jiff involving `Offset` IIRC.)

This will conflict with the already existing method on TimeZone which requires a Timestamp.

**Comment by BurntSushi** [comment]
Ah right, hmmmm. Sorry, I'm on mobile. 

I guess `to_fixed_offset` is fine then.

It probably should also return an error with a message saying the current type of the time zone and that a fixed offset cannot be extracted from it.
