### ISSUE TITLE
Decrease MSRV

### ISSUE THREAD

**Issue by bschoenmaeckers** [BurntSushi/jiff#171]
Currently jiff MSRV is set to 1.70 but it can be lowered and still be compiled correctly. What is your policy on this?

It would be nice if the version could be lowered to 1.63 to make jiff compatible with Pyo3.

**Comment by bschoenmaeckers** [comment]
Nevermind, `OnceLock` requires 1.70+.

**Comment by BurntSushi** [comment]
Yes, correct. IMO, Rust 1.70 is already pretty generous. Rust 1.63 is a very conservative MSRV. I'm guessing it's trying to target Debian. But Debian can just use an older version of Pyo3 that works on their version of Rust.

**Comment by BurntSushi** [comment]
Also, Jiff's MSRV policy is here: https://github.com/BurntSushi/jiff?tab=readme-ov-file#minimum-rust-version-policy
