### ISSUE TITLE
Please provide a rounding mode for "no more than N units shown in friendly output"

### ISSUE THREAD

**Issue by joshtriplett** [BurntSushi/jiff#175]
`Span::round` provides rounding modes for the smallest/largest unit, but the unit has to be specified explicitly.

I'd love to have a rounding mode that ensures no more than N (commonly 2-3) different units are displayed in the friendly output. This allows the precision to depend on the size of the value. For instance, "1 hour 3 minutes" (don't bother showing seconds for times in hours), "1 day 3 hours" (don't bother showing minutes for times in days), and so on.

There are two different common modes to do this. To see the difference, consider the time "2 hours 3 seconds 12 milliseconds", and "no more than 2 different units" rounding. One mode would round this to "2 hours" (because there are no minutes to display); the other would show "2 hours 3 seconds" (2 different units).

**Comment by BurntSushi** [comment]
This seems pretty fiddly to get right IMO. And it should be completely orthogonal to the friendly format. i.e., just an operation on `Span`.

I think I would rather wait for someone to implement this on top of `Span` in a real system. Since as far as I can tell, this can be done with Jiff's existing public API. That is, this isn't a new elementary operation.

**Comment by joshtriplett** [comment]
It's not especially fiddly to get right, especially if you go with the implementation that doesn't support "1 year 3 minutes". It's effectively a rounding operation that sets the largest unit to the largest unit present in the value, and sets the smallest unit relative to the largest unit (e.g. `.largest(Year).num_units(2)`).

**Comment by BurntSushi** [comment]
The specific rules you suggest may not be fiddly, I agree. What's fiddly to me is just how applicable those rules are. I have no real experience formatting relative dates for end users, so I would want to see something real first to avoid designing an API without something very concrete. 

When I think about formatting relative datetimes, I think about it containing a lot of UX driven rules, and it's just not immediately obvious to me what parts Jiff should implement. I'm pretty sure Jiff has all of the "hard" elementary operations available to do whatever you want.

> It's not especially fiddly to get right, especially if you go with the implementation that doesn't support "1 year 3 minutes". It's effectively a rounding operation that sets the largest unit to the largest unit present in the value, and sets the smallest unit relative to the largest unit (e.g. .largest(Year).num_units(2)).

Have you tried doing this with Jiff's API first? That seems like the first step here. I've things that sticks out to me is that Jiff could expose its internal API for getting the largest non-zero unit for convenience reasons.

**Comment by BurntSushi** [comment]
I think [my comment](https://github.com/BurntSushi/jiff/issues/176#issuecomment-2566574229) in #176 basically applies to this one too. Thanks for filing the issue and I'm happy to revisit it in the future!
