### ISSUE TITLE
SpanPrinter: option to skip certain units

### ISSUE THREAD

**Issue by joshtriplett** [BurntSushi/jiff#176]
For `SpanPrinter`, I'd love to have an option to not use specific units for display, such that durations gets displayed using larger numbers of smaller units.

For instance, I might want to never display months, to display things like "1y 211d".

(This would not necessarily be accurate when using Span without being relative to a particular date, but it'd be desirable when displaying a SignedDuration or displaying relative to a particular date.)

**Comment by BurntSushi** [comment]
As mentioned in the docs, the printer is specifically dumb. It just prints whatever is in the `Span` you give it. I think it should stay that way excepting cosmetic options like which labels to use. (This is a key design point copied from Temporal. Specifically that formatting is decoupled from duration manipulations and rounding.)

So for something like this, it ought to be completely decoupled from any sort of printer, and just an operation on `Span` itself. Then _any_ downstream formatter would benefit. 

With that out of the way, can you say more about the high level use case here? And can you point to any real world implementation doing this kind of thing?

**Comment by BurntSushi** [comment]
If you just want to excise months, for example, then I think that one case is easy: 

1. Balance the span up to years. 
2. Record the number of years. 
3. Set the years to zero.
4. Balance the span up to days. 
5. Set the years to what you recorded in (2).

**Comment by joshtriplett** [comment]
Based on your description, I agree that this is doable using the public API.

The use case is wanting to present the duration of a long-running job, in which days will usually be the largest unit encountered, and make sure that the durations are relatively easy to compare . It's easier to compare 27 days with 35 days than it is with "months" thrown into the mix.

**Comment by BurntSushi** [comment]
Yeah I think this is another one of those things where I would rather someone build something tailored to their use case first, and _then_ we can look at that implementation to see if it makes sense for any of it to live in Jiff proper.

**Comment by BurntSushi** [comment]
I'm going to close this for now since this isn't something I'm tracking right now. Since unless I'm mistaken, I do believe this can be done with the API today. If a concrete implementation appears, then we can take a look at that see if it makes sense to move part or all of it into Jiff. It will depend on just how bespoke the code is and how "universal" we judge the need for it to be.
