### ISSUE TITLE
RFC 2822 parsing is not (technically) compliant

### ISSUE THREAD

**Issue by jhpratt** [BurntSushi/jiff#39]
I'll preface this by saying you're going to hate me for this :smile: 

```rust
const S: &str = "  \t Sat,\r\n \
    (\tfoo012FOO!)\
    (\u{1}\u{b}\u{e}\u{7f})\
    (\\\u{1}\\\u{9}\\\u{28}\\\u{29}\\\\u{5c}\\\u{7f})\
    (\\\n\\\u{b})\
    02 \r\n  \r\n Jan 2021 03:04:05 GMT";

fn main() {
    let _ = dbg!(jiff::fmt::rfc2822::parse(S));
}
```

As idiotic as it seems, this _is_ valid under RFC 2822. [Folding white space can contain parenthesized comments](https://datatracker.ietf.org/doc/html/rfc2822#section-3.2.3). I have no idea why this was ever supported, but it is part of the specification.

While obviously a contrived example, I [added this to my test suite](https://github.com/time-rs/time/blob/aca5c3652aff6fc7df3fbd8591c3e324d3a6ffb2/tests/parsing.rs#L100-L112) when I first implemented RFC 2822 support. Though re-reading the relevant part of the spec, I'll have to check whether `time` is even compliant as it's explicitly stated that nested comments are permitted.

**Comment by BurntSushi** [comment]
Yes, I was aware of this when I wrote the parser, but it was unclear to me whether it was worth supporting. I decided to wait until I got a real world case where this matters to do anything about it. But I can add a note to the docs in the interim.

**Comment by jhpratt** [comment]
That's fair! It is obscure to say the least. I felt it was worth mentioning even if you didn't care to support it.
