### ISSUE TITLE
add support for fractional seconds to `jiff::fmt::strtime`

### ISSUE THREAD

**Issue by BurntSushi** [BurntSushi/jiff#54]
This came up when trying to port [`numbat`](https://github.com/sharkdp/numbat) from `chrono` to `jiff`: https://github.com/sharkdp/numbat/pull/511#discussion_r1694241336

Chrono has `%f` and `%.f` specifiers, where I think for fractional seconds, most folks will want `%.f`.

I searched around for how other strtime-like APIs do this, since it's not actually part of the standard `strptime` and `strftime` C APIs.

I like [how `miller` does it](https://github.com/johnkerl/miller/issues/125#issuecomment-292762955), but it doesn't seem quite as flexible as I'd like. And it changes the meaning of, e.g., `%5S`, which today means "pad on the left to 5 places."

Python has a `%f`, but it's limited to microseconds specifically and doesn't deal with the decimal separator.

Looking at Chrono, I actually really like how they do it. In particular, something like `%.f` will match a possibly non-existing fractional component, so that `14:30:01` will be parsed by `%H:%M:%S%.f` just fine, as will `14:30:01.123456789`. And then formatting directives exist to control the precision of the fractional component. And when formatting, `%.f` can expand to the empty string if the fractional number of nanoseconds is `0`.

One place where I want to diverge from Chrono is `%f`. Namely, it isn't a fractional component, even though, e.g., `%3f` is. Namely, `%f` is the number of nanoseconds since the last whole second. But `%3f` is just like `%.3f`, but without the leading dot. The utility of `%3f` more generally is that it would never expand to the empty string. So it would always be present even if it's zero. This would be useful when it's desirable to parse/format datetimes with a mandatory fractional component. Where as `%.f` is desirable for parsing an _optional_ fractional component. And the numbers, e.g., `%.3f`, control precision and not padding. And when no precision options are given, then any trailing zeros (up to nanoseconds) are not printed.

cc @sharkdp Does this sound like it would work for you?

**Comment by sharkdp** [comment]
> Looking at Chrono, I actually really like how they do it. In particular, something like `%.f` will match a possibly non-existing fractional component, so that `14:30:01` will be parsed by `%H:%M:%S%.f` just fine, as will `14:30:01.123456789`.

Exactly. For my particular use case, I definitely like that `%.f` is optional. I can simply use `%S%.f` in all formats that I want to support, and they all work with and without the fractional seconds part.


> One place where I want to diverge from Chrono is `%f`. Namely, it isn't a fractional component, even though, e.g., `%3f` is.

I think the chrono docs are wrong? The following code prints `000000123`, not `123`:
```rs
let dt = chrono::Utc.timestamp_nanos(123);
println!("{}", dt.format("%f"));
```
(https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=fba10b0efa85f8ecfef6498b7dc2ba81)

So `%f` seems to be the same as `%9f`?

I could imagine that the *non*-zero padded version could maybe be useful for a format like `%S second(s) + %F nanosecond(s)`... but yeah. No idea what the actual intention was. I personally don't have a use case for `%f` or `%3f`, only `%.f`.



> cc @sharkdp Does this sound like it would work for you?

Absolutely. Thank you for writing this down! And for this library.

**Comment by BurntSushi** [comment]
All righty, `%.f` should do what you want in `jiff 0.1.2` on crates.io. :-)
