### ISSUE TITLE
Debug impls should not use Printer implementations

### ISSUE THREAD

**Issue by addisoncrump** [BurntSushi/jiff#60]
See #59 for an example; the printer is opinionated and produces sometimes unrepresentative output. Debug implementations should represent *exactly* what is stored in memory for testing purposes.

**Comment by addisoncrump** [comment]
I think the question comes down to "Who will use the Debug implementations?". From my perspective, the Debug impls should be used strictly for debug purposes, i.e. if you want to know the actual content of the data for debug purposes. This is especially relevant due to what you've pointed out: the debug information currently does not provide information that would help someone debug.

It may be appropriate to implement debug s.t. values set to zero are simply omitted and a `finish_non_exhaustive` is used. But ultimately, hiding the units will make things harder to debug, especially since the units are the user-facing API.

**Comment by BurntSushi** [comment]
I don't think it's quite that clear cut. While hiding units _can_ make things harder to debug, showing _too much_ information can also make things harder to debug. I've spent a lot of time debugging Jiff, and I can say with some confidence that showing all units (even when they are zero) makes things incredibly noisy. The output is easily one or two orders magnitude bigger than is necessary in most cases.

I think the most likely path here is to use something other than ISO 8601 as the output format. But I would still want something that is information dense.

**Comment by addisoncrump** [comment]
Hm, okay. Would you consider adding a way to format it with units shown, e.g. with a new type pattern?

**Comment by BurntSushi** [comment]
Even units that are zero? I'd rather not personally. I mean I'm open to it if it becomes a widely requested feature with a solid use case. But for now, I think that can be implemented outside the crate inside the fuzzer if necessary though.

**Comment by addisoncrump** [comment]
Ah, not including units that are zero. I'll add it to the `shim` module.
