### ISSUE TITLE
Optimize the performance of obtaining the default time zone

### ISSUE THREAD

**Issue by 1996fanrui** [BurntSushi/jiff#96]
# Background

`TimeZone::system()` obtains the default time zone, and it may be called frequently by users. 

Especially, `Zoned::now` will call it. In some systems, `Zoned::now` is frequently used to obtain the current time. For example, log system will call it for each log item.

# How long does `TimeZone::system()` need? and why?

After run the benchmark on my Mac, I found `TimeZone::system()` needs `61.665 ns`, its cost mainly consists of 3 parts:

1. TimeZone.clone[1] costs ***9.3 ns***, it clones the TimeZone from cache.
2. Request the read lock[2] costs ***16.88 ns***. (The read lock of cache.)
3. Obtain current time via `Instant::now`[3] costs ***37.3 ns***, the Instant is used for checking whether the cache is expired.

So the `Instant::now`(part 3) takes most of time.

# The idea of optimization

Don't call `Instant::now` during call `TimeZone::system()`, and we could start a light async thread to update the default time zone cache periodically.

Note: if the default time zone is obtained by async thread, we could update it more frequently. For example: update the default TTL from 5 minutes to 20 seconds or less.

[1] https://github.com/BurntSushi/jiff/blob/c659069a2765a5e28ba503ea37e8a2eee4b10a92/src/tz/system/mod.rs#L119
[2] https://github.com/BurntSushi/jiff/blob/c659069a2765a5e28ba503ea37e8a2eee4b10a92/src/tz/system/mod.rs#L104
[3] https://github.com/BurntSushi/jiff/blob/c659069a2765a5e28ba503ea37e8a2eee4b10a92/src/tz/system/mod.rs#L106

**Comment by BurntSushi** [comment]
I don't think we need an issue for every PR. I'm going to close this so that we can focus discussion on the PR.

**Comment by 1996fanrui** [comment]
> I don't think we need an issue for every PR. I'm going to close this so that we can focus discussion on the PR.

thanks for the reminder. 

In some other open source community, the issue is necessary. I got it now, I will avoid issue if it's needed next time.
